# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='dateofbirth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
