# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0002_producer_dateofbirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth')], max_length=4)),
                ('quarter', models.CharField(max_length=1)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_app.producer')),
            ],
        ),
    ]
