# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0004_auto_20180315_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_id', models.CharField(max_length=128, verbose_name='ID')),
                ('mem_name', models.CharField(max_length=128, verbose_name='Name')),
                ('mem_addresse', models.CharField(blank=True, max_length=128, verbose_name='Addresse')),
                ('mem_phone', models.CharField(blank=True, max_length=128, verbose_name='Phone')),
                ('mem_mobile', models.CharField(blank=True, max_length=128, verbose_name='Mobile')),
                ('mem_fax', models.CharField(blank=True, max_length=128, verbose_name='Fax')),
                ('mem_email', models.CharField(blank=True, max_length=128, verbose_name='Email')),
                ('mem_contactperson', models.CharField(blank=True, max_length=128, verbose_name='Contact Name')),
                ('mem_typeofproduct', models.CharField(blank=True, choices=[('leather', 'Leather'), ('synthetic', 'Synthetic'), ('textile', 'Textile')], max_length=32, verbose_name='Type')),
                ('mem_shoestype', models.CharField(blank=True, choices=[('gents', 'Gents Shoes'), ('ladies', 'Ladies Shoes'), ('kids', 'Kids Shoes'), ('leatherbag', 'Leather Bag'), ('garment', 'Garment'), ('gloves', 'Gloves'), ('accessories', 'Accessories')], max_length=32, verbose_name='Product Catagory')),
                ('maleemployee', models.CharField(blank=True, max_length=128, verbose_name='Permanent M. Emp')),
                ('femaleemployee', models.CharField(blank=True, max_length=128, verbose_name='Permanent F. Emp')),
            ],
        ),
        migrations.CreateModel(
            name='network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(blank=True, max_length=128, verbose_name='Name')),
            ],
        ),
        migrations.DeleteModel(
            name='unidocluster_member',
        ),
        migrations.AddField(
            model_name='member',
            name='subnetworkmem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_app.network'),
        ),
    ]
