# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0005_auto_20180315_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Enterprises'},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name': 'Network'},
        ),
        migrations.AlterField(
            model_name='member',
            name='subnetworkmem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_app.Network'),
        ),
    ]
