# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0006_auto_20180315_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clustername', models.CharField(max_length=128, verbose_name='Cluster')),
            ],
            options={
                'verbose_name': 'Clusterr',
            },
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Enterprise', 'verbose_name_plural': 'Enterprises'},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name': 'Network', 'verbose_name_plural': 'Networks'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='subnetworkmem_id',
        ),
        migrations.AddField(
            model_name='member',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_app.Network', verbose_name='Networkk'),
        ),
        migrations.AlterField(
            model_name='network',
            name='network_name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='network',
            name='cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_app.Cluster'),
        ),
    ]
