# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0009_auto_20180315_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='production',
            name='producer',
        ),
        migrations.AlterModelOptions(
            name='cluster',
            options={'verbose_name': 'Cluster'},
        ),
        migrations.AlterField(
            model_name='member',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_app.Network', verbose_name='Network'),
        ),
        migrations.DeleteModel(
            name='producer',
        ),
        migrations.DeleteModel(
            name='production',
        ),
    ]
