# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0010_auto_20180316_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberMachinery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
            ],
        ),
        migrations.AlterModelOptions(
            name='machinery',
            options={'verbose_name': 'Machinery'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='femaleemployee',
        ),
        migrations.RemoveField(
            model_name='member',
            name='maleemployee',
        ),
        migrations.AlterField(
            model_name='member',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_app.Network', verbose_name='Network'),
        ),
        migrations.AddField(
            model_name='membermachinery',
            name='machinery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_app.Machinery'),
        ),
        migrations.AddField(
            model_name='membermachinery',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_app.Member'),
        ),
    ]
