# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0011_auto_20180316_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPerPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='year')),
                ('phase', models.CharField(choices=[('1', 'Jan-Apr'), ('2', 'May-Aug'), ('3', 'Sep-Dec')], max_length=32, verbose_name='Phase')),
                ('permanentmaleemployee', models.IntegerField(verbose_name='Permanent M. Emp')),
                ('permanentfemaleemployee', models.CharField(max_length=128, verbose_name='Permanent F. Emp')),
                ('tempmaleemployee', models.IntegerField(verbose_name='Temporary M. Emp')),
                ('tempfemaleemployee', models.CharField(max_length=128, verbose_name='Temporary F. Emp')),
                ('shoes', models.IntegerField(blank=True, verbose_name='Shoes in Dozen')),
                ('price', models.FloatField(verbose_name='Price')),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_app.Network', verbose_name='Network'),
        ),
        migrations.AlterField(
            model_name='membermachinery',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_app.Member'),
        ),
        migrations.AddField(
            model_name='productionperphase',
            name='Member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_app.Member'),
        ),
    ]
