# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_app', '0012_auto_20180316_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinery',
            options={'verbose_name': 'Machinery', 'verbose_name_plural': 'Machineries'},
        ),
        migrations.RemoveField(
            model_name='productionperphase',
            name='Member',
        ),
        migrations.AddField(
            model_name='productionperphase',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_app.Member', verbose_name='Enterprise'),
        ),
        migrations.AlterField(
            model_name='member',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_app.Network', verbose_name='Network'),
        ),
        migrations.AlterField(
            model_name='membermachinery',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_app.Member'),
        ),
    ]
